language:
  - node_js

node_js:
  - 8

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_install: dpkg --compare-versions `npm -v` ge 6.0 || npm i -g npm@latest

jobs:
  include:
    - stage: test
      install:
        - npm ci
      services:
        - postgresql
      before_script:
        - export NODE_ENV="development"
        - export PGUSER="postgres"
        - export PGPASSWORD=""
        - psql -c "create database traffic_counter"
      script:
        - npx knex migrate:latest
        - npm run lint
        - npm test
    - stage: publish
      install:
        - npm install --production
      script:
        - echo $SSH_PRIVATE_KEY | base64 --decode | openssl aes-256-cbc -K $encrypted_f631e6304a5e_key -iv $encrypted_f631e6304a5e_iv -out ~/.ssh/id_rsa -d
        - chmod 600 ~/.ssh/id_rsa
        - cat .known_hosts > ~/.ssh/known_hosts
        - rsync -azP --delete . deploy@trucktracker.net:~/sites/backend
        - ssh -t deploy@trucktracker.net 'bash -i -c "source /etc/profile; cd sites/backend; npx knex migrate:latest; pm2 reload backend"'

